### ISSUE TITLE
Invalid type for `retry_count` parameter

### ISSUE THREAD

**Issue by 0xMukesh** [frain-dev/convoy.js#10]
The type for the [`retry_count` parameter ](https://github.com/frain-dev/convoy.js/blob/3b615ae84520dbe4e966385242a22bcfd0a46298/src/interfaces/subscription.ts#L14) under the subscription create function is `string` but shouldn't it be `number`? I have created trying a subscription with `retry_count` as a string and got an error saying that "incorrect JSON type for field `retry_config.retry_count`"

![image](https://user-images.githubusercontent.com/90365542/200113144-05794ede-93b2-4fbe-876c-d0c71ef268a5.png)

I have tried sending the request with the `retry_count` parameter as a number instead of a string and it worked.

**Comment by Dotunj** [comment]
Hi @0xMukesh, thanks for pointing this out. We'll update the type for the corresponding field and release an updated version.
